### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by UyNa1t** [aleflabo/MoCoDAD#19]
Dear author, thank you for your open source work.
I encountered the following problem when I ran the training code I and tried to get visual results using wandb and ema：
Traceback (most recent call last):
  File "/root/autodl-tmp/MoCoDAD/train_MoCoDAD.py", line 87, in <module>
    trainer.fit(model=model, train_dataloaders=train_loader, val_dataloaders=val_loader)
  File "/root/miniconda3/envs/mocodad/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/root/miniconda3/envs/mocodad/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 41, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/mocodad/lib/python3.11/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 91, in launch
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/mocodad/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/root/miniconda3/envs/mocodad/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 973, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/mocodad/lib/python3.11/site-packages/pytorch_lightning/trainer/trainer.py", line 1016, in _run_stage
    self.fit_loop.run()
  File "/root/miniconda3/envs/mocodad/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py", line 201, in run
    self.advance()
  File "/root/miniconda3/envs/mocodad/lib/python3.11/site-packages/pytorch_lightning/loops/fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/root/miniconda3/envs/mocodad/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/root/miniconda3/envs/mocodad/lib/python3.11/site-packages/pytorch_lightning/loops/training_epoch_loop.py", line 230, in advance
    call._call_callback_hooks(trainer, "on_train_batch_end", batch_output, batch, batch_idx)
  File "/root/miniconda3/envs/mocodad/lib/python3.11/site-packages/pytorch_lightning/trainer/call.py", line 193, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
TypeError: EMACallback.on_train_batch_end() missing 1 required positional argument: 'dataloader_idx'

 Here are the parameters in my code：
 def on_train_batch_end(self, trainer, pl_module, outputs, batch, batch_idx, dataloader_idx):
     print('Updating weights with EMA')
        self.ema.update(pl_module)
Although I tried to solve it through all the methods found but failed, can you help me solve the question？

**Comment by stdrr** [comment]
Dear @UyNa1t, thank you for your interest in our work, and sorry for the late reply.

Although we have the code for the EMA callback, we didn't use it in the final version. So, you can disable it and train the model without it.

Best regards,
Stefano

**Comment by UyNa1t** [comment]
I am very glad to receive your reply, I have completed the training and verificating operation of your code. Now I would like to realize the visualization picture in your paper, but it is very difficult for me to complete this goal only according to the visualization file you gave, I would like to know if you can add the usable visualization code for this project, thank you very much
